apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  labels:
    app: homepage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: {{IMAGE}}
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 300m
            memory: 1000Mi
          limits:
            cpu: 300m
            memory: 2000Mi