baseURL = 'https://siriusfrk.ru/'
languageCode = 'en-us'
title = 'Sunny comming soon'

# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

[params]
  # LoveIt theme version
  version = "0.2.X"

[menu]
  [[menu.main]]
    name = "Publications"
    url = "/publications"
    title = "Publications"
    weight = 1
  [[menu.main]]
    name = "PhD"
    url = "/phd"
    title = "PhD"
    weight = 1
  [[menu.main]]
    name = "Wishlist"
    url = "wishlist"
    title = "Wishlist"
    weight = 1
  [[menu.main]]
    name = "CV"
    url = "https://docs.google.com/document/d/144KpDzYzrY5QIi4mlA4FLEnj3NdSFjlWtu-LXhzXThw/edit#heading=h.y6sn8imv08xf"
    
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false