
# Change the default theme to be use when building the site with Hugo
theme = "LoveIt"

languageCode = 'en-us'
title = 'Sunny comming soon'


defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false
[languages]
  [languages.ru]
    baseURL = 'https://siriusfrk.ru/'
    contentDir = 'content/ru'
    disabled = false
    languageDirection = 'ltr'
    languageName = 'Русский'
    title = 'Скоро будет солнечно'
    weight = 2
    [languages.ru.params.home.profile]
      subtitle = 'Скоро будет солнечно'
    [languages.ru.params.header.title]
      name = 'Скоро будет солнечно'
    [languages.ru.menus]
      [[languages.ru.menus.main]]
        name = "Посты"
        url = "/posts"
        title = "Посты"
        weight = 1
      [[languages.ru.menus.main]]
        name = "Диссер"
        url = "/phd"
        title = "Диссер"
        weight = 3
      [[languages.ru.menus.main]]
        name = "Вишлист"
        url = "/wishlist"
        title = "Вишлист"
        weight = 4
      [[languages.ru.menus.main]]
        name = "Резюме"
        url = "/cv"
        title = "Резюме"
        weight = 5
  [languages.en]
    baseURL = 'https://siriusfrk.me/'
    contentDir = 'content'
    disabled = false
    languageDirection = 'ltr'
    languageName = 'English'
    title = 'Sunny comming soon'
    weight = 1
    [languages.en.params.home.profile]
      subtitle = 'Sunny comming soon'
    [languages.en.params.header.title]
      name = 'Sunny comming soon'
    [languages.en.menus]
      [[languages.en.menus.main]]
        name = "Posts"
        url = "/posts"
        title = "Posts"
        weight = 1
      [[languages.en.menus.main]]
        name = "PhD"
        url = "/phd"
        title = "PhD"
        weight = 3
      [[languages.en.menus.main]]
        name = "Wishlist"
        url = "/wishlist"
        title = "Wishlist"
        weight = 4
      [[languages.en.menus.main]]
        name = "CV"
        url = "/cv"
        title = "CV"
        weight = 5
[params]
  # LoveIt theme version
  version = "0.2.X"
  gitRepo = "https://github.com/siriusfreak/homepage"
  title = "Sunny comming soon"
  [params.page.code]
    maxShownLines = -1
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = "siriusfrk@gmail.com"
    # LoveIt CHANGED | 0.2.7 title shown in home page (HTML format is supported)
    title = ""
    # subtitle shown in home page (HTML format is supported)
    typeit = true
    # whether to show social links
    social = true
    # LoveIt NEW | 0.2.0 disclaimer (HTML format is supported)
    disclaimer = ""
    [params.social]
      GitHub = "siriusfreak"
      Linkedin = "siriusfreak"
      Instagram = "siriusfreak"
      Telegram = "siriusfreak"
      Gitlab = "siriusfreak"
      ORCID = "0000-0002-2860-2711"
      Phone = "+4915208335740"
      Email = "siriusfrk@gmail.com"




    
# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
